# Generated by Django 5.0.3 on 2024-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
