# Generated by Django 5.0.3 on 2024-05-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipemodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='image',
            new_name='image_url',
        ),
    ]
